version: "3"
services:
    jupyter:
        build: .
        volumes:
            - .:/home/jovyan/work/
        working_dir: /home/jovyan/work/
        ports:
            - 8888:8888
        command: >
            sh -c "
            jupyter notebook --port=8888 --ip=0.0.0.0 --allow-root
            "
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        shm_size: '128gb'
