TEXTS = {
    "0-4": [
        "undefined",
        "Whatcha doing over there, Jo?",
        "Just talking to Teddy.",
        "I gotta run to my meeting!",
        "Can I come, Gramps?",
        "Sure thing, Jo. Grab your notebook and come upstairs!",
        "See you later, Teddy.",
        "I get to go to Gramps's meeting!",
        "Now where did I put my notebook?",
        "\\u00f0\\u0178\\u02dc\\u00b4",
        None,
        "I love these photos of me and Teddy!",
        "Found it!",
        "Gramps is in trouble for losing papers?",
        "This can't be right!",
        "Gramps is a great historian!",
        "Hmm. Button's still not working.",
        "Let's get started. The Wisconsin Wonders exhibit opens tomorrow!",
        "Who wants to investigate the shirt artifact?",
        "Not Leopold here. He's been losing papers lately.",
        "Hey!",
        "It's true, they do keep going missing lately.",
        "See?",
        "Besides, I already figured out the shirt.",
        "It's a women's basketball jersey!",
        "That settles it.",
        "Wells, finish up your report.",
        "Leopold, why don't you help me set up in the Capitol?",
        "We need to talk about that missing paperwork.",
        "Will do, Boss.",
        "Hey Jo, let's take a look at the shirt!",
        "Your grampa is waiting for you in the collection room.",
        "Why don't you go catch up with your grampa?",
        "What a fascinating artifact!",
        "Wow, that's so cool, Gramps!",
        "Can I take a closer look?",
        "Hmmm. Shouldn't you be doing your homework?",
        "It's already all done!",
        "Plus, my teacher said I could help you out for extra credit!",
        "Well, that's good enough for me.",
        "Go ahead, take a peek at the shirt!",
        "This looks like a clue!",
        "I'll record this in my notebook.",
        "Find anything?",
        "Yes! This old slip from 1916.",
        "I knew it!",
        "I'm not so sure that this is a basketball jersey.",
        "Wait, you mean Wells is wrong?!",
        "Could be. But we need evidence!",
        "Why don't you head to the Basketball Center and rustle up some clues?",
        "Sure!",
        "I'll be at the Capitol. Let me know if you find anything!",
        "Better check back later.",
        "That's it!",
        "The slip is from 1916 but the team didn't start until 1974!",
        "Our shirt is too old to be a basketball jersey!",
        "I need to get to the Capitol and tell Gramps!",
        "I should see what Grampa is up to!",
        "Ugh. Meetings are so boring.",
        "Grab your notebook and come upstairs!",
        "Hang tight, Teddy.",
        "I'll hurry back and then we can go exploring!",
        "Well, Leopold here is always losing papers...",
        "Ha. Told you so!",
        "Can we hurry up, Gramps?",
        "Teddy and I were gonna go climb that huge tree out back!",
        "Hmmm. Don't forget about your homework.",
        "Your teacher said you missed 7 assignments in a row!",
        "So? History is boring!",
        "I suppose historians are boring, too?",
        "No way, Gramps. You're the best!",
        "Then do it for me!",
        "Your teacher said you could help me for extra credit.",
        "A boring old shirt.",
        "Just this old slip from 1916.",
        "Do I have to?",
        "Um... what did you want me to do again?",
        "Head over to the Basketball Center.",
        "Hopefully you can find some clues!",
        "Meetings are BORING!",
        "I feel like I'm forgetting something.",
        "Gramps is the best historian ever!",
        "This button never works!",
        "Why don't you go play with your grampa?",
        "Look at that! It's the bee's knees!",
        "Well, I did SOME of those. I just couldn't find them!",
        "Did you do all of them?",
        "No... because history is boring!",
        "Hooray, a boring old shirt.",
        "Hot Dog! I knew it!",
        "Ooh, I like clues!",
        "Hopefully you can rustle up some clues!",
        "I should go talk to Gramps!",
        "Yes! This cool old slip from 1916.",
        "I should see what Gramps is up to!",
        "Gramps said to look for clues. Better look around.",
        "Have a look at the artifact!",
        "Come on, Jo!",
        "Meet me back in my office and we'll get started!",
    ],
    "5-12": [
        None,
        "What are you still doing here,  Jolie?",
        "Go find your grampa and get to work!",
        "Oh no!",
        "undefined",
        "What happened here?!",
        "I don't know!",
        "I got here and the whole place was a mess!",
        "Can you help me tidy up?",
        "Teddy's scarf! Somebody must've taken him!",
        "Try not to panic, Jo.",
        "Maybe he just got scared and ran off.",
        "But he never goes anywhere without his scarf!",
        "I think he's in trouble!",
        "Is this your coffee, Gramps?",
        "Nope, that's from Bean Town. I only drink Holdgers!",
        "Who could've done this?",
        "It must've been Wells.",
        "He's always trying to get you in trouble, and he doesn't like animals!",
        "Slow down, Jo.",
        "But what if Wells kidnapped Teddy?",
        "Then we need evidence.",
        "You're right, Gramps. Let's investigate!",
        "I'm afraid my papers have gone missing in this mess.",
        "You'll have to get started without me.",
        "Okay. I'll find Teddy!",
        "And I'll figure out the shirt, too.",
        "I knew I could count on you, Jo!",
        "Why don't you go upstairs and see the archivist?",
        "He's our expert record keeper.",
        "I need your help!",
        "Who are you?",
        "I'm Leopold's grandkid!",
        "Sorry, I'm too busy for kids right now.",
        "Now if only I could read this thing.",
        "Can't believe I lost my reading glasses.",
        "I bet the archivist could use this!",
        "Ah, that's better!",
        "Did you have a question?",
        "Yes! I was wondering-",
        "Wait a minute!",
        "Where did you get that coffee?",
        "Oh, that's from Bean Town.",
        "I ran into Wells there this morning.",
        "Wells? I knew it!",
        "Do you know anything about this slip?",
        "I found it on an old shirt.",
        "An old shirt? Try the university.",
        "You can talk to a textile expert there.",
        "What's a textile expert?",
        "They study clothes and fabric.",
        "Great! Thanks for the help!",
        "Head over to the university.",
        "Hello there!",
        "Wow! What is all this stuff?",
        "It's our Norwegian Craft exhibit!",
        "Can I give you the tour?",
        "Sorry, I'm in a hurry.",
        "Do you know what this slip is?",
        "Looks like a dry cleaning receipt.",
        "Thanks.",
        "Now I Just need to find all the cleaners from way back in 1916.",
        "Maybe I can help!",
        "I've got a stack of business cards from my favorite cleaners.",
        "Why don't you take a look?",
        "This place was around in 1916! I can start there!",
        "You haven't seen any badgers around here, have you?",
        "Badgers? No.",
        "Okay. Thanks anyway.",
        "Hi! How can I help you?",
        "I need to find the owner of this slip.",
        "Well, I can't show our log books to just anybody.",
        "Please?",
        "It's for Grampa Leo. He's a historian!",
        "Leo... you mean Leopold?",
        "Your gramps is awesome! Always full of stories.",
        "Guess it couldn't hurt to let you take a look.",
        "Here's the log book.",
        "It's a match!",
        "Theodora Youmans must be the owner!",
        "Do you know who Theodora Youmans is?",
        "Hmmm... not sure. Why don't you try the library?",
        "Thanks for the help!",
        "Oh, hello there!",
        "How can I help you?",
        "Have you seen a badger around here?",
        "I'm afraid not.",
        "Please let me know if you do.",
        "I'm also looking for Theodora Youmans. Have you heard of her?",
        "Theodora Youmans? Of course!",
        "Check out our microfiche. It's right through that door.",
        "Youmans was a suffragist!",
        "She helped get votes for women!",
        "Wells! What was he doing here? I should ask the librarian.",
        "What was Wells doing here?",
        "He was looking for a taxidermist.",
        "What's a taxidermist?",
        "Not sure. Here, let me look it up.",
        "\\Taxidermy: the art of preparing, stuffing, and mounting the skins of animals.\\",
        "Oh no... Teddy!",
        "Can you help me find Wells?",
        "You could ask the archivist. He knows everybody!",
        "Jolie! I was hoping you'd stop by. Any news on the shirt artifact?",
        "I haven't quite figured it out just yet...",
        "Well, get on it. I'm counting on you and your gramps to figure this out!",
        "Can you help me? I need to find Wells!",
        "I haven't seen him.",
        "Please? This is really important.",
        "Sorry, can't help you.",
        "Do you have any info on Theodora Youmans?",
        "Theodora Youmans? Is that who owned the shirt?",
        "Yep.",
        "Why didn't you say so?",
        "Youmans was a suffragist here in Wisconsin.",
        "She led marches and helped women get the right to vote!",
        "Wait a sec. Women couldn't vote?!",
        "Nope. But Youmans and other suffragists worked hard to change that.",
        "Thanks to them, Wisconsin was the first state to approve votes for women!",
        "Wow!",
        "Here's a call number to find more info in the Stacks.",
        "Where are the Stacks?",
        "Right outside the door.",
        "Hey, this is Youmans!",
        "And look! She's wearing the shirt!",
        "I should go to the Capitol and tell everyone!",
        "Better check back later.",
        "Hmm. Button's still not working.",
        "What should I do first?",
        "Head upstairs and talk to the archivist. He might be able to help!",
        "What the-",
        "I have an idea.",
        "He's wrong about old shirts and his name rhymes with \\smells\\...",
        "BUT WELLS STOLE TEDDY!",
        "Could be. But we need evidence.",
        "Fine. Let's investigate!",
        "Don't worry, Gramps. I'll find Teddy!",
        "Please let me know if you do. It's important!",
        "I need to find Wells right away! Do you know where he is?",
        "I need to find Wells!!!",
        "I can't calm down. This is important!",
        "Ugh. Fine.",
        "I love these photos of me and Teddy.",
        "I should stay and look for clues!",
        "Where should I go again?",
        "You could try the archivist. Maybe he can help you find Wells!",
        "Hi, Mrs. M.",
        "I don't need that right now.",
        "I got here and the whole place was ransacked!",
        "Hold your horses, Jo.",
        "*grumble grumble*",
        "And you are?",
        "I don't have time for kids.",
        "Now if only I could read this thing. Blasted tiny letters...",
        "Knew what?",
        "Did you have a question or not?",
        "Yes!",
        "You're still here? I'm trying to work!",
        "Run along to the university.",
        "Ooh, thanks!",
        "Now I just need to find all the cleaners from wayyyy back in 1916.",
        "Yikes... this could take a while.",
        "Hi! *cough*",
        "Can you help-",
        "*cough cough*",
        "Can you help me-",
        "*COUGH COUGH COUGH*",
        "Um, are you okay?",
        "Oh, I'm fine! Just a little hoarse.",
        "Ha! What do you call a pony with a sore throat?",
        "Huh?",
        "A little horse!",
        "Ha! You're funny.",
        "I got that one from my Gramps!",
        "Can you help me? I need to find the owner of this slip.",
        "Yup, that's him!",
        "Unless you're too busy horsing around.",
        "Ha! Good one.",
        "You look like you're on a mission.",
        "Two missions, actually!",
        "Oh my!",
        "I need to find Wells right away!! Do you know where he is?",
        "Calm down, kid. I haven't seen him.",
        "I should help Gramps clean.",
        "Maybe there's a clue in this mess!",
        "Poor Gramps! I should make sure he's okay.",
        "The archivist said I should look in the stacks.",
        "Yeah. Thanks anyway.",
        "What are you waiting for? The Stacks are right outside the door.",
        "This button never works!",
        "Are you okay?",
        "Weren't you going to check out our microfiche?",
        "I'm sure you'll find Theodora in there somewhere!",
        "Well? What are you still doing here?",
        "So much cleaning to do...",
        "I used to have a magnifying glass around here\\u00e2\\u20ac\\u00a6",
        "But I hear the museum's got one on the loose!",
        "Did you drop something, Dear? There's a card on the floor.",
        "Take a look!",
        "It's such a nice fall day.",
        "I found it!",
        "Theodora wearing the shirt!",
        "You better get to the capitol!",
        "Nice decorations.",
        "Nice seeing you, Jolie!",
        "Did you drop something, Dear?",
        "I should find out if she can help me!",
        "Ooh, nice decorations!",
        "The libarian said I could find some information on Youmans in here...",
        "I should ask the librarian why Wells was here.",
        "I wonder if there's a clue in those business cards...",
        "Thanks. Did you figure out the shirt?",
        "Welcome back, Jolie. Did you figure out the shirt?",
        "I should check that logbook to see who owned this slip...",
        "AND I know who took Teddy!",
        "Who is Teddy?",
        "And where's your grampa?",
        "Sorry for the delay, Boss.",
        "I had some cleaning up to do in my office.",
        "Mrs. M, I think Wells kidnapped Teddy.",
        "And he messed up Gramps's office, too!",
        "One step at a time, Jo.",
        "Did you figure out the shirt?",
        "I knew you could do it, Jo!",
        "Now can I tell you what happened to Teddy?",
        "He needs our help!",
        "Sorry I'm late.",
        "Wells! Where's Teddy? Is he okay?",
        "I figured out that you kidnapped him!",
        "Easy, Jo.",
        "Why don't you prove your case?",
        "It'll be okay, Jo. We'll find Teddy!",
        "Nice work on the shirt, Jolie!",
        "Leopold, can you run back to the museum?",
        "Sounds good, Boss.",
        "Jo, meet me back at my office.",
        "I hope you find your badger, kid.",
        "Here I am!",
        "Wells sabotaged Gramps!",
        "AND he stole Teddy!",
    ],
    "13-22": [
        None,
        "Jo!",
        "Check out the next artifact!",
        "What is it?",
        "I think it's a flag! Pretty interesting, huh?",
        "It's really cool, Gramps. But I'm worried about Teddy.",
        "He's still missing!",
        "We'll find him, Jo.",
        "Want to look for more clues?",
        "We'll find Teddy.",
        "We just have to keep our eyes open!",
        "Hey, look at those scratches!",
        "The kidnapper probably took Teddy on the elevator!",
        "You're right, Jo!",
        "Why isn't the button working?",
        "We'll need a key card.",
        "I had one, but Teddy chewed it up.",
        "I've got Wells's ID!",
        "What should we do next?",
        "I need to take the artifact upstairs. Why don't you investigate those scratch marks?",
        "Okay. I'll try.",
        "Teddy, here I come!",
        "I wonder whose glasses these are.",
        "Teddy!!!",
        "Hang on. I'll get you out of there!",
        "Whoever lost these glasses probably took Teddy!",
        "How can I find out whose glasses these are?",
        "Oh! There was a staff directory in the entryway!",
        "I'll go look at everyone's pictures!",
        "Those are the same glasses!",
        "The archivist must've taken Teddy!",
        "Yes! It's the key for Teddy's cage!",
        "I found the key!",
        "Come on, let's get out of here!",
        "Here's your scarf back!",
        "undefined",
        "Hey!",
        "What are you doing down here?",
        "And how did that badger get free?",
        "I'm here to rescue my friend!",
        "What's going on here?",
        "Thanks for coming, Boss.",
        "I told you!",
        "I captured a badger in our museum!",
        "He's been eating my lunch every day this week!",
        "He has??",
        "I've seen him eating homework and important papers, too.",
        "Jolie- keep your badger under control, or he'll have to go.",
        "And you, Frank-",
        "You can't just steal Jolie's pet.",
        "Ugh. Fine.",
        "Alright, Jolie. Back to work.",
        "Your grampa is waiting for you in the collection room.",
        "Come on, Teddy. Let's go help Gramps!",
        "Let's go help Gramps!",
        "Gramps must be up in the collection room.",
        "Let's go find him!",
        "Teddy! I'm glad to see you.",
        "The archivist had him locked up!",
        "Poor badger.",
        "You're becoming quite the detective, Jo.",
        "Notice any clues about this flag?",
        "Well... it looks hand-stitched.",
        "Good catch!",
        "Go on, tell the boss what you found!",
        "I'm telling you, Boss. Taxidermy is the way to go!",
        "Nonsense. I want live animals at the exhibit, not stuffed ones.",
        "Ah, Jolie! I'm glad you're here.",
        "I'm putting you in charge of the flag case.",
        "Make sure to get some old photos for the exhibit, like last time!",
        "Wait! Can't I do it?",
        "The symbol on the flag looks sort of like a deer hoof.",
        "It could be an early design for the Wisconsin state flag!",
        "Wells, you already have a job to do.",
        "What now, kid?",
        "Do you really think that symbol is a deer hoof?",
        "Not sure.",
        "Do you know where I can find a deer expert?",
        "Hmm. You could try the Aldo Leopold Wildlife Center.",
        "I have to head over there and check out the animals.",
        "I'll ride with you!",
        "Come on, kid. Let's go.",
        "Head over to the Wildlife Center!",
        "I'm sure they'll be able to help.",
        "People sure drink a lot of coffee around here.",
        "I can't believe this.",
        "Ugh...",
        "Oh no! What happened to that crane?",
        "Her beak is stuck in a coffee cup.",
        "It's lucky we found her.",
        "Ugh! Those cups are all over the place.",
        "I need to get her free. She won't hold still!",
        "Can Teddy and I help?",
        "Sure! Give it a try.",
        "Careful. That beak is sharp!",
        "We need to calm her down, Teddy.",
        "Any ideas?",
        "\\u00f0\\u0178\\u00a6\\u2014",
        "Oh yeah, cranes eat insects!",
        "Luckily there are tons of insects around here...",
        "Got one!",
        "Maybe she'll let me take off the cup!",
        "It's OK, girl! Look, I found you a cricket!",
        "You did it! Thanks, kid.",
        "Can I help you with anything?",
        "I'm investigating this symbol.",
        "Does it look like a deer hoof?",
        "There's a diagram of animal tracks over there.",
        "Go take a look!",
        "That hoofprint doesn't match the flag!",
        "Thanks for your help, kid!",
        "So? What'd you find out?",
        "Looks like it's not a deer hoof.",
        "Oh no. If I don't impress the boss soon,  I'm gonna get fired!",
        "Hey, Wells...",
        "I think I might be able to help you.",
        "No thanks. I don't need help from kids.",
        "Are you sure? I know where you can find a real, live badger for the exhibit!",
        "Wait! What?! Really?",
        "Wells, meet Teddy.",
        "\\u00f0\\u0178\\u02dc\\u0160",
        "He says he'd be willing to help out.",
        "Yes!!!",
        "We still need to figure out that flag. Do you know anyone who could help?",
        "Hmm. Let's see...",
        "Actually, I went to school with somebody who LOVES old flags.",
        "Why don't you go talk to her? I'll let her know you're coming.",
        "Hey, nice dog! What breed is he?",
        "Actually, he's a badger.",
        "Oh, cool! I've never seen a badger in real life.",
        "You've got a million flags here!",
        "Yep. I'm a vexillophile!",
        "What's a vexillophile? ",
        "It just means flag expert. How can I help?",
        "I'm investigating this flag.",
        "Can you take a look?",
        "Hey, I've seen that symbol before! Check it out!",
        "\\Ecology flag, by Ron Cobb.\\",
        "It's an ecology flag!",
        "Do you know what this flag was used for?",
        "I'm not sure.",
        "If I were you, I'd go to the library and do some digging.",
        "Good idea. Thanks!",
        "Welcome back, Dear! How can I help you?",
        "I need to learn more about this flag!",
        "It has something to do with ecology.",
        "Hmm... those stripes remind me of the American flag.",
        "Your flag must have been part of a national movement!",
        "Go check the microfiche. Maybe you'll find something!",
        "Hey! That's Governor Nelson in front of our flag!",
        "I found the flag! Governor Nelson used it on the first Earth Day!",
        "Wow! You figured it out!",
        "Now I just need some old photos, like last time.",
        "The boss is gonna love it!",
        "You could try the archives.",
        "Though the archivist might be too busy to help...",
        "Okay. Thanks!",
        "What are you doing here?",
        "We're looking for some photos.",
        "It's for the flag display!",
        "Wait a minute...",
        "YOU'RE the new history detective everybody's talking about?",
        "Teddy's helping too.",
        "What kind of photos do you need?",
        "Something to do with ecology and Wisconsin.",
        "Here's a call number for the Stacks. Go find some photos.",
        "Look at all those activists!",
        "This is perfect for the exhibit.",
        "I should go to the Capitol and tell Mrs. M!",
        "It's locked!",
        "You haven't seen any badgers around here, have you?",
        "Badgers? No.",
        "Okay. Thanks anyway.",
        "Jolie! I was hoping you'd stop by. Any news on the flag artifact?",
        "I haven't quite figured it out just yet...",
        "Well, get on it. I'm counting on you to figure this out!",
        "Nice seeing you, Jolie!",
        "It's such a nice fall day.",
        "I love these photos of me and Teddy.",
        "Hey, this is Youmans!",
        "And look! She's wearing the shirt!",
        "I should go to the Capitol and tell everyone!",
        "Why don't you go talk to the boss?",
        "She's right outside.",
        "My friend is a flag expert.",
        "She should be able to help you out.",
        "There are some old newspapers loaded up in the microfiche.",
        "The Stacks are right outside the door. Go find some photos!",
        "I don't have time for this, Gramps.",
        "Teddy is still missing!",
        "Let's follow those scratch marks!",
        "I can't go with you. I need to take the artifact upstairs.",
        "It's okay, Gramps. I'll go by myself.",
        "You stole Teddy! How could you?!",
        "No he hasn't!",
        "Yes, he has. I've seen him eating homework and important papers, too.",
        "Come on, Teddy.",
        "Let's go find Gramps!",
        "I think I can help with your animal problem.",
        "Ha! I don't need your help.",
        "Fine. Then I guess you don't want a real, live badger for the exhibit.",
        "Oh, trust me. He'll make time.",
        "Head back to the museum. Your gramps is waiting for you.",
        "I think it's a flag! Pretty spiffy, eh?",
        "Great Scott, you're right!",
        "Jo! I can't go with you. I need to take the artifact upstairs.",
        "\\u00f0\\u0178\\u02dc\\u00ad",
        "\\u00e2\\u009d\\u00a4\\u00ef\\u00b8\\u008f",
        "GRRRRRRR",
        "GAH! And what is THAT doing out of its cage?!",
        "\\u00f0\\u0178\\u02dc\\u0090",
        "Teddy! Did you really eat his lunch?",
        "Did you steal Gramps's paperwork too?!",
        "And my homework?!?!",
        "See?!",
        "That thing's a monster!",
        "I don't have time for this.",
        "YEAH!",
        "Wait- me?",
        "You can't just steal Jolie's pet. Don't you know badgers are protected animals?",
        "Besides, he looks friendly to me.",
        "Wha?!",
        "\\u00f0\\u0178\\u02dc\\u009d",
        "Teddy! I'm sure glad to see you.",
        "Gadzooks! Poor critter.",
        "Aha! Good catch, Jo.",
        "Not sure. Do I look like a deer expert to you?",
        "Ugh. I have to head over there and check out the animals.",
        "FINE. That possum better not scratch my leather seats...",
        "He's a badger!",
        "\\u00f0\\u0178\\u00a7\\u02dc",
        "Yoga does sound nice.",
        "But cranes can't do yoga, Teddy!",
        "\\u00f0\\u0178\\u008d\\u00a9",
        "Cranes don't eat donuts!",
        "Besides, you just ate my last snack.",
        "Gah. I can't believe this.",
        "I'm a historian, not a zookeeper!",
        "And this place is dirty, and itchy, and-",
        "I love it!",
        "Of course you do. You've got a rodent following you around.",
        "Actually, badgers aren't rodents-",
        "Whatever.",
        "Great. Just great. Could this day get any worse?!",
        "Yes!!! I'm saved!",
        "A real, live ferret!",
        "He's. A. Badger.",
        "And we still need to figure out that flag!",
        "Fine, fine. Let's see...",
        "A vexy-wha?",
        "Ooh... \\Ecology flag, by Ron Cobb.\\",
        "The boss is gonna love it!!!",
        "You again! Don't let him hurt me!",
        "\\u00f0\\u0178\\u2122\\u201e",
        "Actually, we're just here for some photos.",
        "Guess so!",
        "YOU?!",
        "Just please, don't let your badger eat them!",
        "There should be some info about that symbol in my book.",
        "Yeah. Thanks anyway.",
        "I'll be in the collection room. Come find me when you're ready to check out the artifact.",
        "Good luck!",
        "Better check back later.",
        "What?!",
        "Can I ride with you?",
        "Don't worry, he won't! (And he's a badger, by the way.)",
        "Ugh... I think that lynx is looking at me funny.",
        "Don't worry, Teddy won't eat your lunch anymore!",
        "We're just looking for photos for the flag display.",
        "But I hear the museum's got one on the loose!",
        "I should check out that pair of glasses.",
        "I should ask the librarian where to go next.",
        "Check out the archives. They've got tons of old photos!",
        "Come on, kid. You're slowing me down.",
        "What is it, Teddy?",
        "Oh no... they got sick from polluted water?",
        "Poor foxes!",
        "Jolie! Where have you been?",
        "The exhibit opens tomorrow.",
        "Wells got in trouble for littering at the Wildlife Center.",
        "Thanks!",
        "Are you going home now? Tomorrow's the big day!",
        "Huh?",
        "He got a park named after him? Cool!",
    ],
}

FQIDS = {
    "0-4": [
        "intro",
        "gramps",
        "teddy",
        "photo",
        "fqid_None",
        "notebook",
        "retirement_letter",
        "tobasement",
        "janitor",
        "toentry",
        "groupconvo",
        "report",
        "boss",
        "wells",
        "directory",
        "tocollection",
        "cs",
        "tunic",
        "tunic.hub.slip",
        "tostacks",
        "outtolunch",
        "tocloset",
        "tomap",
        "tunic.historicalsociety",
        "tunic.kohlcenter",
        "plaque",
        "plaque.face.date",
        "togrampa",
        "tunic.capitol_0",
        "chap1_finale",
        "chap1_finale_c",
        "block_tocollection",
        "doorblock",
        "block_tomap2",
        "block_tomap1",
        "block_0",
    ],
    "5-12": [
        "boss",
        "fqid_None",
        "toentry",
        "tunic.historicalsociety",
        "tobasement",
        "tocloset_dirty",
        "what_happened",
        "gramps",
        "trigger_scarf",
        "trigger_coffee",
        "tomap",
        "tunic.capitol_1",
        "tostacks",
        "tofrontdesk",
        "archivist",
        "magnify",
        "tunic.humanecology",
        "worker",
        "businesscards",
        "businesscards.card_0.next",
        "businesscards.card_1.next",
        "businesscards.card_bingo.next",
        "businesscards.card_bingo.bingo",
        "tohallway",
        "tunic.drycleaner",
        "logbook",
        "logbook.page.bingo",
        "tunic.library",
        "tomicrofiche",
        "reader",
        "reader.paper0.next",
        "reader.paper1.next",
        "reader.paper2.bingo",
        "wellsbadge",
        "journals",
        "journals.hub.topics",
        "journals.pic_0.next",
        "journals.pic_1.next",
        "journals.pic_2.bingo",
        "chap2_finale_c",
        "outtolunch",
        "janitor",
        "tunic.kohlcenter",
        "reader.paper2.next",
        "directory",
        "journals.pic_2.next",
        "tunic.capitol_0",
        "reader.paper1.prev",
        "reader.paper0.prev",
        "photo",
        "block_0",
        "block_magnify",
        "door_block_clean",
        "door_block_talk",
        "reader.paper2.prev",
        "block",
        "tocollection",
        "tunic",
        "plaque",
        "tunic.hub.slip",
        "block_badge",
        "block_badge_2",
        "block_1",
        "chap2_finale",
    ],
    "13-22": [
        "fqid_None",
        "toentry",
        "tunic.drycleaner",
        "tunic.historicalsociety",
        "tunic.capitol_1",
        "tunic.library",
        "tobasement",
        "ch3start",
        "seescratches",
        "gramps",
        "tocage",
        "glasses",
        "teddy",
        "tostacks",
        "directory",
        "directory.closeup.archivist",
        "tofrontdesk",
        "key",
        "unlockdoor",
        "confrontation",
        "savedteddy",
        "tocollectionflag",
        "groupconvo_flag",
        "wells",
        "boss",
        "tomap",
        "tunic.capitol_2",
        "tunic.wildlife",
        "coffee",
        "crane_ranger",
        "remove_cup",
        "expert",
        "tracks",
        "tracks.hub.deer",
        "tunic.flaghouse",
        "flag_girl",
        "colorbook",
        "worker",
        "tomicrofiche",
        "reader_flag",
        "reader_flag.paper0.next",
        "reader_flag.paper1.next",
        "reader_flag.paper2.bingo",
        "archivist_glasses",
        "journals_flag",
        "journals_flag.hub.topics_old",
        "journals_flag.hub.topics",
        "journals_flag.pic_0.bingo",
        "journals_flag.pic_0.next",
        "chap4_finale_c",
        "lockeddoor",
        "tocloset_dirty",
        "tunic.humanecology",
        "tunic.kohlcenter",
        "tohallway",
        "photo",
        "plaque",
        "journals",
        "journals.hub.topics",
        "journals.pic_0.next",
        "journals.pic_1.next",
        "journals.pic_2.bingo",
        "journals.pic_2.next",
        "businesscards",
        "businesscards.card_0.next",
        "businesscards.card_1.next",
        "logbook",
        "reader",
        "reader.paper0.next",
        "reader.paper1.next",
        "reader.paper2.prev",
        "reader.paper2.next",
        "reader.paper0.prev",
        "reader_flag.paper1.prev",
        "journals_flag.pic_0_old.next",
        "journals_flag.pic_1_old.next",
        "tocollection",
        "tunic",
        "tunic.hub.slip",
        "journals_flag.pic_1.bingo",
        "journals_flag.pic_1.next",
        "journals_flag.pic_2.bingo",
        "journals_flag.pic_2.next",
        "reader_flag.paper2.next",
        "businesscards.card_bingo.next",
        "reader_flag.paper0.prev",
        "journals_flag.pic_2_old.next",
        "outtolunch",
        "need_glasses",
        "block_nelson",
        "reader_flag.paper2.prev",
        "reader.paper1.prev",
        "fox",
    ],
}


ROOM_FQIDS = {
    "0-4": [
        "tunic.historicalsociety.closet",
        "tunic.historicalsociety.basement",
        "tunic.historicalsociety.entry",
        "tunic.historicalsociety.collection",
        "tunic.historicalsociety.stacks",
        "tunic.kohlcenter.halloffame",
        "tunic.capitol_0.hall",
    ],
    "5-12": [
        "tunic.capitol_0.hall",
        "tunic.historicalsociety.entry",
        "tunic.historicalsociety.basement",
        "tunic.historicalsociety.closet_dirty",
        "tunic.historicalsociety.stacks",
        "tunic.historicalsociety.frontdesk",
        "tunic.humanecology.frontdesk",
        "tunic.drycleaner.frontdesk",
        "tunic.library.frontdesk",
        "tunic.library.microfiche",
        "tunic.capitol_1.hall",
        "tunic.historicalsociety.collection",
        "tunic.kohlcenter.halloffame",
    ],
    "13-22": [
        "tunic.capitol_1.hall",
        "tunic.historicalsociety.entry",
        "tunic.historicalsociety.basement",
        "tunic.historicalsociety.cage",
        "tunic.historicalsociety.stacks",
        "tunic.historicalsociety.frontdesk",
        "tunic.historicalsociety.collection_flag",
        "tunic.wildlife.center",
        "tunic.flaghouse.entry",
        "tunic.library.frontdesk",
        "tunic.library.microfiche",
        "tunic.capitol_2.hall",
        "tunic.historicalsociety.closet_dirty",
        "tunic.humanecology.frontdesk",
        "tunic.kohlcenter.halloffame",
        "tunic.drycleaner.frontdesk",
        "tunic.historicalsociety.collection",
    ],
}

FLAG_EVENTS_TEXTS_PAIRS = {
    "0-4": [
        ["tunic.historicalsociety.closet.gramps.intro_0_cs_0", "tunic.historicalsociety.closet.notebook"],
        ["tunic.historicalsociety.closet.notebook", "tunic.historicalsociety.entry.groupconvo"],
        ["tunic.historicalsociety.entry.boss.talktogramps", "tunic.historicalsociety.collection.cs"],
        ["tunic.historicalsociety.collection.cs", "tunic.historicalsociety.collection.tunic.slip"],
        ["tunic.historicalsociety.collection.tunic.slip", "tunic.historicalsociety.collection.gramps.found"],
        ["tunic.historicalsociety.collection.gramps.found", "tunic.kohlcenter.halloffame.plaque.face.date"],
    ],
    "5-12": [
        ["tunic.historicalsociety.closet_dirty.what_happened", "tunic.historicalsociety.closet_dirty.gramps.news"],
        ["tunic.historicalsociety.closet_dirty.gramps.news", "tunic.historicalsociety.frontdesk.archivist.hello"],
        ["tunic.historicalsociety.frontdesk.archivist.hello", "tunic.historicalsociety.frontdesk.magnify"],
        ["tunic.historicalsociety.frontdesk.magnify", "tunic.historicalsociety.frontdesk.archivist.have_glass"],
        ["tunic.historicalsociety.frontdesk.archivist.have_glass", "tunic.humanecology.frontdesk.worker.intro"],
        ["tunic.humanecology.frontdesk.worker.intro", "tunic.humanecology.frontdesk.businesscards.card_bingo.bingo"],
        ["tunic.humanecology.frontdesk.businesscards.card_bingo.bingo", "tunic.drycleaner.frontdesk.worker.hub"],
        ["tunic.drycleaner.frontdesk.worker.hub", "tunic.drycleaner.frontdesk.logbook.page.bingo"],
        ["tunic.drycleaner.frontdesk.logbook.page.bingo", "tunic.drycleaner.frontdesk.worker.done"],
        ["tunic.drycleaner.frontdesk.worker.done", "tunic.library.frontdesk.worker.hello"],
        ["tunic.library.frontdesk.worker.hello", "tunic.library.microfiche.reader.paper2.bingo"],
        ["tunic.library.microfiche.reader.paper2.bingo", "tunic.library.frontdesk.wellsbadge.hub"],
        ["tunic.library.frontdesk.wellsbadge.hub", "tunic.library.frontdesk.worker.wells"],
        ["tunic.library.frontdesk.worker.wells", "tunic.historicalsociety.frontdesk.archivist.newspaper"],
        ["tunic.historicalsociety.frontdesk.archivist.newspaper", "tunic.historicalsociety.stacks.journals.pic_2.bingo"],
    ],
    "13-22": [
        ["tunic.capitol_1.hall.boss.writeitup", "tunic.historicalsociety.basement.ch3start"],
        ["tunic.historicalsociety.basement.ch3start", "tunic.historicalsociety.basement.seescratches"],
        ["tunic.historicalsociety.basement.seescratches", "tunic.historicalsociety.frontdesk.key"],
        ["tunic.historicalsociety.frontdesk.key", "tunic.historicalsociety.cage.unlockdoor"],
        ["tunic.historicalsociety.cage.unlockdoor", "tunic.historicalsociety.cage.confrontation"],
        ["tunic.historicalsociety.cage.confrontation", "tunic.historicalsociety.basement.savedteddy"],
        ["tunic.historicalsociety.basement.savedteddy", "tunic.historicalsociety.collection_flag.gramps.flag"],
        ["tunic.historicalsociety.collection_flag.gramps.flag", "tunic.historicalsociety.entry.groupconvo_flag"],
        ["tunic.historicalsociety.entry.groupconvo_flag", "tunic.wildlife.center.crane_ranger.crane"],
        ["tunic.wildlife.center.crane_ranger.crane", "tunic.wildlife.center.remove_cup"],
        ["tunic.wildlife.center.remove_cup", "tunic.wildlife.center.expert.removed_cup"],
        ["tunic.wildlife.center.expert.removed_cup", "tunic.wildlife.center.tracks.hub.deer"],
        ["tunic.wildlife.center.tracks.hub.deer", "tunic.wildlife.center.wells.nodeer"],
        ["tunic.wildlife.center.wells.nodeer", "tunic.flaghouse.entry.flag_girl.hello"],
        ["tunic.flaghouse.entry.flag_girl.hello", "tunic.flaghouse.entry.colorbook"],
        ["tunic.flaghouse.entry.colorbook", "tunic.flaghouse.entry.flag_girl.symbol"],
        ["tunic.flaghouse.entry.flag_girl.symbol", "tunic.library.frontdesk.worker.nelson"],
        ["tunic.library.frontdesk.worker.nelson", "tunic.historicalsociety.frontdesk.archivist_glasses.confrontation"],
        ["tunic.historicalsociety.frontdesk.archivist_glasses.confrontation", "tunic.historicalsociety.stacks.journals_flag.pic_0.bingo"],
    ],
}


FE_AGG_TARGETS = {
    "text": TEXTS,
    "fqid": FQIDS,
    "room_fqid": ROOM_FQIDS,
}
